---
apiVersion: v1
kind: Service
metadata:
  name: Score-Prediction-Service
spec:
  selector:
    app: web-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Prediction-Deployment
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: Prediction-Container
          image: manoharshetty507/ml-flask-web-app:v1
          ports:
            - containerPort: 8080
