apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: manoharshetty507/ml-flask-web-app:v1
      ports:
        - containerPort: 3000
